openapi: 3.0.0
components:
  schemas:
    TimeslipRouting:
      type: object
      properties:
        oid:
          type: number
          description: System Generated Unique Key
        timeslipEmployeeSourceOID:
          type: number
          description: Timeslip Employee Source OID
        timeslipCOTPaymentOID:
          type: number
          description: Timeslip Class of time Payment OID 
        queueID:
          type: string
          description: Queue ID to which COT payment is being routed
        reviewReasonCode:
          type: string
          description: Review Reason for COT Payment Routing

    TimeslipRoutingList:
      type: object
      properties:
        timeslipRoutingCodeList:
            $ref: '#/components/schemas/TimeslipRouting'
   
    ServiceResponseVO:
      type: object
      properties:
        responseStatusCode:
          type: string
          description: Response Status code
          example: OK
        httpStatusCode:
          type: number
          format: int64
          description: HTTP Status code
          example: 200
        message:
          type: string
          description: Service Response Message- A User friendly message
          example: Data Saved/updated/Deleted Successfully 
        data:
          $ref: '#/components/schemas/PageDataResponse'
    
    PageDataResponse:
      type: object
      properties:
        name:
          type: string
          description: Name page
        description:
          type: string
          description: Description
        screenName:
          type: string
          description: Screen Name
        profileType:
          type: string
          description: Screen Profile Type
        screenType:
          type: string
          description: Screen Type
        sections:
          type: array
          items:
            $ref: '#/components/schemas/Section'
        searchResultCount:
          type: number
          description: Search Result count
        searchResultMsg: 
          type: string
          description: Search Result Message
        
    Section:
      type: object
      properties:
        name:
          type: string
          description: Section name
        type:
          type: string
          description: Section Type
        order:
          type: number
          description: Section Order
        label:
          type: string
          description: Section Name
        fields:
          type: array
          items:
            $ref: '#/components/schemas/FieldDataDTO'
        attributes: 
          type: array
          items:
            $ref: '#/components/schemas/Attribute'
        rows:
          type: array
          items:
            $ref: '#/components/schemas/RowDTO'
        searchResultCount:
          type: number
          description: Search Result count
        searchResultMsg: 
          type: string
          description: Search Result Message
        headerAdded:
          type: boolean
        errorCode:
          type: string
          description: Error Code if service returns Validation Error
          
    FieldDataDTO:
      type: object
      properties:
        fieldName: 
          type: string
          description: Field Name as DTO
        label:
          type: string
          description: Label name
        order:
          type: number
          description: Order Of the field
        valueLabel:
          type: string
          description: Value Label name
        value:
          type: string
          description: Field Value
        attributes: 
          type: array
          items:
            $ref: '#/components/schemas/Attribute'
        button:
          type: boolean
          description: Is a flag to denote weather it is a button or not
          
    Attribute:
      type: object
      properties:
        name: 
          type: string
          description: Attribute name
        value:
          type: string
          description: Attribute Value

    RowDTO:
      type: object
      properties:
        columns:
          type: array
          items:
            $ref: '#/components/schemas/ColumnDTO'
        
    ColumnDTO:
      type: object
      properties:
        name: 
          type: string
          description: Field Name
        value:
          type: string
          description: Field Value
        shouldDisplay:
          type: boolean
          description: Flag to say it should display or not
