openapi: 3.0.0
components:
  schemas:
    TimeslipRouting:
      type: object
      properties:
        oid:
          type: number
          description: System Generated Unique Key
        timeslipEmployeeSourceOID:
          type: number
          description: Timeslip Employee Source OID
        timeslipCOTPaymentOID:
          type: number
          description: Timeslip Class of time Payment OID 
        queueID:
          type: string
          description: Queue ID to which COT payment is being routed
        reviewReasonCode:
          type: string
          description: Review Reason for COT Payment Routing
