openapi: 3.0.0
components:
  schemas:
    TimeslipRouting:
      type: object
      name: TimeslipRouting
      properties:
        oid:
          type: number
          description: System Generated Unique Key
        timeslipEmployeeSourceOID:
          type: number
          description: Timeslip Employee Source OID
        timeslipCOTPaymentOID:
          type: number
          description: Timeslip Class of time Payment OID 
        queueID:
          type: string
          description: Queue ID to which COT payment is being routed
        reviewReasonCode:
          type: string
          description: Review Reason for COT Payment Routing
    PageDataResponse:
      type: object
      properties:
        name:
          type: string
          description: Name page
        description:
          type: string
          description: Description
        screenName:
          type: string
          description: Screen Name
        profileType:
          type: string
          description: Screen Profile Type
        screenType:
          type: string
          description: Screen Type
        searchResultCount:
          type: number
          description: Search Result count
        searchResultMsg: 
          type: string
          description: Search Result Message      
